### PR TITLE
Add .gitignore

### PR DESCRIPTION
**Pull request by Kyrela**
Based on [`https://github.com/github/gitignore/blob/main/VisualStudio.gitignore`](https://github.com/github/gitignore/blob/main/VisualStudio.gitignore), manually added `.idea/` exclusion l23

### CODE REVIEW

**Comment by BetaWRLD** [comment]
I use git exclusion instead of .gitignore.

**Comment by Kyrela** [comment]
As `.git/info/exclude` is local, I feel like a `.gitignore` would help maintain a clean and open-for-contribution repo, as other people don't have access to these exclusions and could accidentally commit changes containing unwanted files.
I suggest you to put the content of your `.git/info/exclude` in a `.gitignore`

**Comment by BetaWRLD** [comment]
I think I will merge this, and keep my exclusion as it is.

**Comment by Kyrela** [comment]
Do as you want ; but keep in mind that if you want to exclude something, most people will want to exclude it too, unless it's files that you manually added for a reason or another.
You should but every ignore line of your `exclude` that is relative to generated files/IDEs&Tools in the `.gitignore`, and keep only "local" ignores in `exclude` - both _can_ and, in fact, _should_ be used.
Here's more resources about both solutions and when to use one or another in the context of colaborative development:
- [StackOverflow - When would you use .git/info/exclude instead of .gitignore to exclude files?](https://stackoverflow.com/questions/22906851/when-would-you-use-git-info-exclude-instead-of-gitignore-to-exclude-files)
- [gitignore(5) Manual Page](https://mirrors.edge.kernel.org/pub/software/scm/git/docs/gitignore.html)
- [Best Practices for Git Ignore](https://blog.iqandreas.com/git/best-practices-for-git-ignore/)
- [GitHub - Ignoring files](https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files)

**Pull request merged**
